# Generated by Django 4.0.5 on 2022-06-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_followerscount_delete_likepost_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
