# Generated by Django 4.0.5 on 2022-07-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_of_like',
            new_name='no_of_likes',
        ),
    ]
